### ISSUE TITLE
First time using it, getting an `Other files have been modified; changes not deployed` error

### ISSUE THREAD

**Issue by loureirorg** [10up/action-wordpress-plugin-asset-update#24] opened 2020-08-02 19:15 UTC
**Describe the bug**
After installing the action on my repo, I created a `trunk` branch, changed the `readme.txt` file, and submitted the changes, getting an `Other files have been modified; changes not deployed` error.

Commit: https://github.com/loureirorg/wordpress-plugin-export-users/commit/635870e97f5469382c04e8caf30df8dfdcc6b310
Failed action: https://github.com/loureirorg/wordpress-plugin-export-users/runs/938044443?check_suite_focus=true

**Steps to Reproduce**
1. Create a `trunk` branch (`git checkout -b trunk`);
2. Change the `readme.txt` file (`echo "\n" >> readme.txt`);
3. Submit the changes (`git add readme.txt; git commit -m "Test"; git push origin trunk`);
4. On GitHub Actions see the error `Other files have been modified; changes not deployed`;

**Expected behavior**
Changes made on WordPress.org.

**Additional context**
I use the `WordPress.org Plugin Deploy` as my deploy tool I don't have any problems with it. Recently I decided to try `WordPress.org Plugin Readme/Assets Update` for small changes on the `readme.txt` file. 

I strongly believe I am missing something and that's not an actual bug. Maybe it's because I didn't have a `trunk` repository and thus it is trying to submit all the contents at once. 

I actually don't use a `trunk` for any of my Git projects - instead, I create a new branch and once the code is ready to be merged I do a PR. So maybe I am not using the `trunk` approach as it was intended to by this tool.

**Comment by Tropicalista** [comment] 2020-12-17 14:01
Same error here. Have you found a solution?

**Comment by jeffpaul** [comment] 2020-12-17 15:09
@loureirorg @Tropicalista you'll want to note the first line specifically in the readme (bolded text to call out likely issue):
> This Action commits any readme and WordPress.org-specific assets changes in your specified branch to the WordPress.org plugin repository **if no other changes have been made since the last deployment to WordPress.org.**

Unfortunately that Action run log is no longer available, but I suspect that there were other changes in the branch that cause the action to fail (as designed).

@Tropicalista do you have a link to a commit and action log that I can review to try and help triage?

**Comment by Tropicalista** [comment] 2020-12-17 16:00
@jeffpaul I'm using it here: https://github.com/Tropicalista/animista/actions/runs/428246716

**Comment by jeffpaul** [comment] 2020-12-17 18:51
@Tropicalista you don't need the `SLUG` line if your GitHub repo matches the SVN repo (which yours appears to).  Also, the same comment for @loureirorg above applies for you as it appears there are other changes in your `master` branch that haven't been deployed so the asset/readme update action will fail (as designed).

**Comment by ocean90** [comment] 2020-12-18 08:02
This sounds similar to #12. Would be nice to to get that fixed once the remaining questions on the issue have been clarified.

**Comment by JohnRDOrazio** [comment] 2021-04-18 17:13
I'm having a bit of trouble myself. I recently created a github copy of my svn repo. And after a certain amount of development I am ready for a new release. I created a release, and the tag was successfully pushed to SVN with the tag-deploy.yml action (using 10up/action-wordpress-plugin-deploy@1.5.0).
Then I modified the readme.txt, but on saving, the readme-deploy.yml action failed because it said it could not change into the directory .wordpress-org. Then I read about having the .wordpress-org directory as a mirror of the `assets` folder on the SVN repo. So I created this directory and added the assets to it, and pushed to github master/trunk branch. I also created a README.md alongside readme.txt for a better experience on Github. But now if I make any small changes to readme.txt in order to get the action to trigger, I'm getting the error that other changes have been made to the repo.

The only changes made since the last tag were the addition of the .wordpress-org folder with asset files, and a change to README.md. How can I force the action, so that I can get my latest release published on SVN?
____
UPDATE: I wound up simply creating another release. So I have two releases which are pretty much the same, but the first of these never actually got released on the WordPress plugins repository since the stable tag never pointed at it. Doing yet another release made sure the changes by adding the assets folder and all didn't prevent the release from happening the second time round.

**Comment by zaerl** [comment] 2022-12-01 08:24
This fix: https://github.com/10up/action-wordpress-plugin-deploy/pull/96 should be applied to https://github.com/10up/action-wordpress-plugin-asset-update/blob/develop/deploy.sh as well.

See: https://github.com/10up/action-wordpress-plugin-deploy/issues/88

**Comment by zaerl** [comment] 2022-12-05 06:49
Solved with https://github.com/10up/action-wordpress-plugin-asset-update/pull/46.

**Closed as completed** 2022-12-08 04:03 UTC
Labels: type:bug
